development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ykoxluojkknrmq:1_mDzimXuQeYPUU6ZWtFQzojoi@ec2-54-163-226-155.compute-1.amazonaws.com:5432/d3kolfor0of856
