# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e190a38e3d87adfbe7750aac2e2f4f6a1f4832aa3f24831a0a43fe04efc22bfd71ec00295a0951f92a587cbb0b35a8c45398d8ec8c746948e1e5a77bb4b3789c

test:
  secret_key_base: 40e3ecd8caf4d5fdb3956d30dc50e51f91373a62366dc1a58841433c97b6547637cea379725007d7d28d923e192f30888a5bf1f8e235ee77a30a3795681de4ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
